name: Windows - LiteManager Setup

on:
  workflow_dispatch:

jobs:
  build:
    name: Setup LiteManager
    runs-on: windows-latest

    steps:
      - name: Download Essentials Script
        run: |
          echo "Downloading Downloads.bat..."
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          if (!(Test-Path "Downloads.bat")) {
            Write-Error "Downloads.bat not found after download."
            exit 1
          }

      - name: Run Essentials Script
        run: |
          echo "Running Downloads.bat..."
          cmd /c Downloads.bat

      - name: Check for show.bat
        run: |
          if (!(Test-Path "show.bat")) {
            Write-Error "show.bat not found."
            exit 1
          }

      - name: Connect to LiteManager
        run: |
          echo "Running show.bat..."
          cmd /c show.bat

      - name: Check for loop.bat
        run: |
          if (!(Test-Path "loop.bat")) {
            Write-Error "loop.bat not found."
            exit 1
          }

      - name: Start Time Counter
        run: |
          echo "Running loop.bat..."
          cmd /c loop.bat
